# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bear-classifier',
                'doc_host': 'https://bfx23.github.io',
                'git_url': 'https://github.com/bfx23/bear-classifier',
                'lib_path': 'bear_classifier'},
  'syms': {'bear_classifier.bear_classifier': {}}}
